export const UPCOMING_LAUNCH_DETAILS = "UPCOMING_LAUNCH_DETAILS";
export const PREVIOUS_LAUNCH_DETAILS = "PREVIOUS_LAUNCH_DETAILS";
export const FETCH_ROCKETS_DETAILS = 'FETCH_ROCKETS_DETAILS';
export const DIALOG_STATE = 'DIALOG_STATE';